
args<-commandArgs(TRUE)
dir=args[1]
setwd(dir)
watershed_name=args[2]
pit_file=paste(watershed_name,"fel.tif",sep="")
file_name=paste(watershed_name,"parspc.txt",sep="")
sink(file_name)
cat("f", ",",0,",", "f.tif",sep="","\n")
cat("ko",",", 0, ",","ko.tif",sep="","\n")
cat("dth1",",", 0,",", "dth1.tif",sep="","\n")
cat("dth2", ",",0,",", "dth2.tif",sep="","\n")
cat("soildepth", ",",0,",", "sd.tif",sep="","\n")
cat("dth2", ",",0,",", "dth2.tif",sep="","\n")
cat("c",",", -1,",", 1,sep="","\n")
cat("psif",",", 0,",", "psif.tif",sep="","\n")
cat("chv", ",",-1,",", 360,sep="","\n")
cat("cc",",",1,",", "lulcmmef.tif",",","lutluc.txt",",",1,sep="","\n")
cat("cr",",",1,",", "lulcmmef.tif",",","lutluc.txt",",",2,sep="","\n")
cat("albedo",",",1,",", "lulcmmef.tif",",","lutluc.txt",",",3,sep="","\n")
cat("LapseRate", ",",-1,",", 0.0053,sep="","\n")
cat("AverageElevation",",", 0,",", pit_file,sep="","\n")
cat("ImperviousFraction", ",",-1,",", 0.00,sep="","\n")
cat("TileDrainedFraction", ",",-1,",", 0.00,sep="","\n")
cat("DitchDrainedFraction",",", -1,",", 0.00,sep="","\n")
cat("TileCoeff", ",",-1, ",",0.00,sep="","\n")
cat("DitchCoef", ",",-1,",", 0.00,sep="","\n")
cat("IrrigatedFraction", ",",-1,",",0.00,sep="","\n")
cat("SprinklerFractionofIrrigation",",", -1, ",",0.00,sep="","\n")
cat("IrrigationEfficiency", ",",-1,",",0.00,sep="","\n")
cat("D_Thres", ",",-1, ",",0.00,sep="","\n")
cat("Z_Max", ",",-1,",", 0.0042,sep="","\n")
cat("D_Goal", ",",-1,",", 0.00,sep="","\n")
cat("kc_1",",",1,",", "lulcmmef.tif",",","lutkc.txt",",",1,sep="","\n")
cat("kc_2",",",1, ",","lulcmmef.tif",",","lutkc.txt",",",2,sep="","\n")
cat("kc_3",",",1, ",","lulcmmef.tif",",","lutkc.txt",",",3,sep="","\n")
cat("kc_4",",",1,",", "lulcmmef.tif",",","lutkc.txt",",",4,sep="","\n")
cat("kc_5",",",1,",", "lulcmmef.tif",",","lutkc.txt",",",5,sep="","\n")
cat("kc_6",",",1, ",","lulcmmef.tif",",","lutkc.txt",",",6,sep="","\n")
cat("kc_7",",",1, ",","lulcmmef.tif",",","lutkc.txt",",",7,sep="","\n")
cat("kc_8",",",1, ",","lulcmmef.tif",",","lutkc.txt",",",8,sep="","\n")
cat("kc_9",",",1, ",","lulcmmef.tif",",","lutkc.txt",",",9,sep="","\n")
cat("kc_10",",",1, ",","lulcmmef.tif",",","lutkc.txt",",",10,sep="","\n")
cat("kc_11",",",1, ",","lulcmmef.tif",",","lutkc.txt",",",11,sep="","\n")
cat("kc_12",",",1, ",","lulcmmef.tif",",","lutkc.txt",",",12,sep="","\n")
cat("Transmissivity",",", 0,",", "Trans.tif",sep="","\n")
cat("FractionForest",",", -1, ",",0.00,sep="")
sink(file_name,append=TRUE)
sink()